apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-multi
  template:
    metadata:
      labels:
        app: web-multi
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
              name: nginx
        - name: multitool
          image: wbitt/network-multitool:latest
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: multitool
---
apiVersion: v1
kind: Service
metadata:
  name: web-multi-svc
spec:
  selector:
    app: web-multi
  ports:
    - name: nginx
      port: 80
      targetPort: 80
    - name: multitool
      port: 8080
      targetPort: 8080
  type: ClusterIP
